Numpy : Practice Problem

1. Extract all odd numbers from arr


In [9]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[arr%2==1])

[1 3 5 7 9]


2. Replace all odd numbers in arr with -1

In [71]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==1]=-1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


3. Convert a 1D array to a 2D array with 2 rows

In [10]:
arr=np.arange(10)
arr = np.reshape(arr,(2,5))
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


4. Stack arrays a and b vertically

In [11]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c=np.vstack((a,b))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


5. Get all items between 5 and 10 from a

In [16]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a = a[(a>=5)*(a<=10)]
print(a)

[ 6  9 10]


Desired Output:
(array([6, 9, 10]),)

6. Create a null vector of size 10 but the fifth value which is 1.

In [18]:
x = np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49.

In [19]:
a = np.arange(10,49)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


8. Create a 10x10 array with random values and find the minimum and maximum values.

In [73]:
a = np.random.random((10,10))
print(a)
amin,amax = a.min() ,a.max()
print("\n")
print("amin:",amin,"\n","amax:",amax)

[[0.0894899  0.17343655 0.79419915 0.73442419 0.85183097 0.58771043
  0.11049866 0.51498949 0.11045434 0.74150013]
 [0.26576555 0.63674447 0.01129178 0.44043869 0.89547261 0.08283636
  0.81119386 0.42429766 0.15140019 0.0340575 ]
 [0.79516733 0.13285536 0.71501817 0.7045163  0.49751069 0.10342156
  0.51416314 0.62768292 0.51741837 0.2646944 ]
 [0.08669599 0.71982457 0.20394139 0.36166381 0.77768541 0.88104223
  0.30279369 0.15038277 0.738161   0.91215899]
 [0.93625649 0.02064955 0.47273838 0.04603304 0.05370535 0.63778575
  0.07300841 0.99143063 0.77952984 0.69963216]
 [0.12899799 0.27169419 0.59999301 0.61864553 0.5629452  0.65277491
  0.23425673 0.31603636 0.74561474 0.87271601]
 [0.48282864 0.36801228 0.09654366 0.68811374 0.03414638 0.06848656
  0.90950728 0.55707376 0.29502118 0.73311837]
 [0.27085767 0.86978179 0.66154845 0.39455122 0.15043161 0.82079047
  0.46202803 0.47646677 0.59314937 0.76600005]
 [0.99333839 0.35521962 0.06053264 0.25356564 0.2306351  0.73361236
  0.62446521

9. Create a 3*3 matrix and print it's transpose matrix

In [34]:
a = np.arange(0,9)
b = a.reshape(3,3)
print(b)
print("\n")
c = b.transpose()
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[0 3 6]
 [1 4 7]
 [2 5 8]]


10. Create two arrays of 2-D and find dot product of it.

In [46]:
a = np.arange(1,5)
b = a.reshape(2,2)
c = np.arange(6,10)
d = c.reshape(2,2)
print(b)
print(d)
x = b.dot(b,d)
print("\n",x)

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]

 [[ 7 10]
 [15 22]]


11. Compute the maximum for each row in the given array.

In [74]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a,"\n")
a = np.amax(a,axis = 1)
print(a)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]] 

[9 8 6 3 9]


12. Select 3rd & 5th row and 3rd & 4th columns

In [81]:
data = np.random.randint(10,100,(5,4))
data


IndexError: index 4 is out of bounds for axis 1 with size 4

13. Convert below matrix into vector

In [53]:
matrix = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
print(matrix.flatten())

[1 2 3 4 5 6 7 8 9]


14. The product of two inverse matrix is identical matrix,prove

In [55]:
# create a square matrix
m = np.array([[2,3],
              [2,4]])


array([[ 2. , -1.5],
       [-1. ,  1. ]])

15. Create a matrix from a uniform distribution over [0, 1)

In [75]:
a = np.random.uniform(1,0,5)
print(a)

[0.93631896 0.37568811 0.47665226 0.43770374 0.99418281]
